### ISSUE TITLE
Issue Regarding Nonce Already Used and Connection with metamask

### ISSUE THREAD

**Issue by text4lilac** [kohlivarun5/nfty#307]
Hello sir, in my SwiftUI App i am using wallet connect library version 1 dapp client side code to integrate wallet connection and also refer your code . connection is successfull. There are two issue i am getting:

1. when using rainbow wallet app, everytime i call eth_sendTransaction method i am getting nonce already used
2. when using metamask, when i call eth_sendTransaction method nothing happens, i mean no popup comes in metamask

is there a workaround?

and also how do i fetch proper chainid when i use metamsk or rainbow app?

**Comment by kohlivarun5** [comment]
Not related to NFTYgo, please check WalletConnect diocumentation
